site_name: prueva-bk
site_description: Esta es una prueba de descpicion prueva-bk
plugins:
  - techdocs-core
nav:
  - Home: index.md
  - Setup:
    - Project Structure: 
      - Espa√±ol: setup/project-structure.md
      - Ingles: setup/project-structure.md
    - Installation: setup/installation.md
  - Usage:
    - Running the App: usage/running-the-app.md
    - Changing Language: usage/changing-language.md
  - Components:
    - App Component: components/app.md
    - MarkdownContent Component: components/markdown-content.md
  - Configuration:
    - i18next Configuration: configuration/i18next.md